import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  ///'admin/dashboard/main'
  // Admin Modules
  {
    path: '/admin/dashboard',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },

  {
    path: '',
    title: 'Student Information',//'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/employees/allEmployees',
        title: 'MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/employees/add-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/employees/edit-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.EDIT-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/employees/employee-profile',
        title: 'MENUITEMS.EMPLOYEES.LIST.PROFILE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/clients/all-clients',
        title: 'MENUITEMS.CLIENTS.LIST.ALL-CLIENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/clients/add-client',
        title: 'MENUITEMS.CLIENTS.LIST.ADD-CLIENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/clients/edit-client',
        title: 'MENUITEMS.CLIENTS.LIST.EDIT-CLIENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Student Payments', //'MENUITEMS.ACCOUNTS.TEXT',
    iconType: 'feather',
    icon: 'book-open',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/accounts/all-payment',
        title: 'MENUITEMS.ACCOUNTS.LIST.ALL-PAYMENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/accounts/add-payment',
        title: 'MENUITEMS.ACCOUNTS.LIST.ADD-PAYMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/accounts/invoice',
        title: 'MENUITEMS.ACCOUNTS.LIST.INVOICE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Advanced Postings',//'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/payroll/payslip',
        title: 'MENUITEMS.PAYROLL.LIST.PAYSLIP',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  //
  // {
  //   path: '/admin/leads',
  //   title: 'MENUITEMS.LEADERS.TEXT',
  //   iconType: 'feather',
  //   icon: 'users',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Admin'],
  //   submenu: [],
  // },
  {
    path: '',
    title: 'Bills',
    iconType: 'feather',
    icon: 'award',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/jobs/jobs-list',
        title: 'MENUITEMS.JOBS.LIST.JOBS_LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/jobs/resumes',
        title: 'MENUITEMS.JOBS.LIST.RESUMES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/jobs/candidates',
        title: 'MENUITEMS.JOBS.LIST.CANDIDATES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/jobs/shortlist',
        title: 'MENUITEMS.JOBS.LIST.SHORTLIST_CANDIDATES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.REPORTS.TEXT',
    iconType: 'feather',
    icon: 'file-text',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/reports/leave-report',
        title: 'MENUITEMS.REPORTS.LIST.LEAVE_REPORT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/reports/expense-report',
        title: 'MENUITEMS.REPORTS.LIST.EXPENSE_REPORT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  // Employee Modules
  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/attendance',
    title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myleaves',
    title: 'MENUITEMS.EMPLOYEE.MY-LEAVES',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myteam',
    title: 'MENUITEMS.EMPLOYEE.MYTEAM',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myprojects',
    title: 'MENUITEMS.EMPLOYEE.MYPROJECTS',
    iconType: 'feather',
    icon: 'database',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/mytasks',
    title: 'MENUITEMS.EMPLOYEE.MYTASKS',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/settings',
    title: 'MENUITEMS.EMPLOYEE.SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/chat',
    title: 'MENUITEMS.EMPLOYEE.CHAT',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  // Client Modules
  {
    path: '/client/dashboard',
    title: 'MENUITEMS.CLIENT.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.CLIENT.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [
      {
        path: '/client/projects/myProjects',
        title: 'MENUITEMS.CLIENT.PROJECTS.LIST.MY-PROJECTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/client/projects/projectDetails',
        title: 'MENUITEMS.CLIENT.PROJECTS.LIST.PROJECT-DETAILS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '/client/billing',
    title: 'MENUITEMS.CLIENT.BILLING',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },

  {
    path: '/client/settings',
    title: 'MENUITEMS.CLIENT.SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },

  // Common Modules

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee'],
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: 'New',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin', 'Employee'],
    submenu: [],
  },

  {
    path: 'contacts',
    title: 'Contacts',
    iconType: 'feather',
    icon: 'user-plus',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee'],
    submenu: [],
  },



  {
    path: '',
    title: 'Components',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },

];
